if (!window.audioFiles) window.audioFiles = {}; 
window.audioFiles.audioFileList = []; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/1up.ogg', fileLocation: 'audioFiles/file0.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['1up.ogg']) window.folderStructure['res']['snd']['1up.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/airship.ogg', fileLocation: 'audioFiles/file1.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['airship.ogg']) window.folderStructure['res']['snd']['airship.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/bell.ogg', fileLocation: 'audioFiles/file2.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['bell.ogg']) window.folderStructure['res']['snd']['bell.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/blackdiamond.ogg', fileLocation: 'audioFiles/file3.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['blackdiamond.ogg']) window.folderStructure['res']['snd']['blackdiamond.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/bump.ogg', fileLocation: 'audioFiles/file4.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['bump.ogg']) window.folderStructure['res']['snd']['bump.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/castle.ogg', fileLocation: 'audioFiles/file5.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['castle.ogg']) window.folderStructure['res']['snd']['castle.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/cave.ogg', fileLocation: 'audioFiles/file6.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['cave.ogg']) window.folderStructure['res']['snd']['cave.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/chipdisko.ogg', fileLocation: 'audioFiles/file7.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['chipdisko.ogg']) window.folderStructure['res']['snd']['chipdisko.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/coin.ogg', fileLocation: 'audioFiles/file8.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['coin.ogg']) window.folderStructure['res']['snd']['coin.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/deluge.ogg', fileLocation: 'audioFiles/file9.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['deluge.ogg']) window.folderStructure['res']['snd']['deluge.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/die.ogg', fileLocation: 'audioFiles/file10.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['die.ogg']) window.folderStructure['res']['snd']['die.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/explodeF.ogg', fileLocation: 'audioFiles/file11.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['explodeF.ogg']) window.folderStructure['res']['snd']['explodeF.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/fireball.ogg', fileLocation: 'audioFiles/file12.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['fireball.ogg']) window.folderStructure['res']['snd']['fireball.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/fizz.ogg', fileLocation: 'audioFiles/file13.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['fizz.ogg']) window.folderStructure['res']['snd']['fizz.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/flame.ogg', fileLocation: 'audioFiles/file14.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['flame.ogg']) window.folderStructure['res']['snd']['flame.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/flap.ogg', fileLocation: 'audioFiles/file15.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['flap.ogg']) window.folderStructure['res']['snd']['flap.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/gulp.ogg', fileLocation: 'audioFiles/file16.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['gulp.ogg']) window.folderStructure['res']['snd']['gulp.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/halloween.ogg', fileLocation: 'audioFiles/file17.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['halloween.ogg']) window.folderStructure['res']['snd']['halloween.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/heal.ogg', fileLocation: 'audioFiles/file18.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['heal.ogg']) window.folderStructure['res']['snd']['heal.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/hurt.ogg', fileLocation: 'audioFiles/file19.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['hurt.ogg']) window.folderStructure['res']['snd']['hurt.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/icebreak.ogg', fileLocation: 'audioFiles/file20.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['icebreak.ogg']) window.folderStructure['res']['snd']['icebreak.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/iceland.ogg', fileLocation: 'audioFiles/file21.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['iceland.ogg']) window.folderStructure['res']['snd']['iceland.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/icicle.ogg', fileLocation: 'audioFiles/file22.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['icicle.ogg']) window.folderStructure['res']['snd']['icicle.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/invincible.ogg', fileLocation: 'audioFiles/file23.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['invincible.ogg']) window.folderStructure['res']['snd']['invincible.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/jump.ogg', fileLocation: 'audioFiles/file24.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['jump.ogg']) window.folderStructure['res']['snd']['jump.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/kick.ogg', fileLocation: 'audioFiles/file25.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['kick.ogg']) window.folderStructure['res']['snd']['kick.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/overworld.ogg', fileLocation: 'audioFiles/file26.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['overworld.ogg']) window.folderStructure['res']['snd']['overworld.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/puzzle.ogg', fileLocation: 'audioFiles/file27.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['puzzle.ogg']) window.folderStructure['res']['snd']['puzzle.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/retro-2.ogg', fileLocation: 'audioFiles/file28.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['retro-2.ogg']) window.folderStructure['res']['snd']['retro-2.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/slide.ogg', fileLocation: 'audioFiles/file29.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['slide.ogg']) window.folderStructure['res']['snd']['slide.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/spook.ogg', fileLocation: 'audioFiles/file30.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['spook.ogg']) window.folderStructure['res']['snd']['spook.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/spooky_enchantment.ogg', fileLocation: 'audioFiles/file31.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['spooky_enchantment.ogg']) window.folderStructure['res']['snd']['spooky_enchantment.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/squish.ogg', fileLocation: 'audioFiles/file32.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['squish.ogg']) window.folderStructure['res']['snd']['squish.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/supertuxtheme.ogg', fileLocation: 'audioFiles/file33.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['supertuxtheme.ogg']) window.folderStructure['res']['snd']['supertuxtheme.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/trampoline.ogg', fileLocation: 'audioFiles/file34.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['trampoline.ogg']) window.folderStructure['res']['snd']['trampoline.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/village-mixed.ogg', fileLocation: 'audioFiles/file35.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['village-mixed.ogg']) window.folderStructure['res']['snd']['village-mixed.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/wallkick.ogg', fileLocation: 'audioFiles/file36.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['wallkick.ogg']) window.folderStructure['res']['snd']['wallkick.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/warning.ogg', fileLocation: 'audioFiles/file37.ogg', isSound: true }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['warning.ogg']) window.folderStructure['res']['snd']['warning.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/win.ogg', fileLocation: 'audioFiles/file38.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['win.ogg']) window.folderStructure['res']['snd']['win.ogg'] = {}; 
window.audioFiles.audioFileList.push({ originalName: 'res/snd/winter_wonderland.ogg', fileLocation: 'audioFiles/file39.ogg', isSound: false }); 
 if (!window.folderStructure) window.folderStructure = {}; 
if (!window.folderStructure['res']) window.folderStructure['res'] = {}; 
if (!window.folderStructure['res']['snd']) window.folderStructure['res']['snd'] = {}; 
if (!window.folderStructure['res']['snd']['winter_wonderland.ogg']) window.folderStructure['res']['snd']['winter_wonderland.ogg'] = {}; 
